# Default values for the Jira Chart.
# This is a YAML-formatted file.

# Declare variables with default values to be passed into your templates.
# To override them, you need to (a) either adjust this file, or (b) provide your own values file,
# which overrides the values found here.

Replicas: 1
ContainerName: jira

RBAC:
  Enabled: true

Datacenter:
  Enabled: false

#Â to add certs inside the docker container
Certs:
  Enabled: true
  # The secret below must be created in advance to contain all your certs
  # It will be mounted to the path you specify below inside the container
  # to create the secret, you can use the following command:
  # kubectl create secret generic my-top-secret --from-file=path/to/certs/dir --namespace my-ns
  SecretName: my-top-secret
  MountPath: /var/atlassian/certificates/

Image:
  Name: "praqma/jira-server"
  Tag: "latest"
  ImagePullPolicy: "Always"
  PrivateRegistry: true
  PullSecret: "docker-hub-credentials"

ContainerPort: 8080

EnvVars:
  X_PROXY_NAME: "localhost"
  X_PROXY_PORT: "8080"
  X_PROXY_SCHEME: "http"
  X_CONTEXT_PATH: ""
  ADDITIONAL_CONNECTOR: "false"
  JAVA_OPTS: ""
  K8S_ENABLE_ETC_HOSTS_UPDATE: ""
  K8S_PROXY_INTERNAL_FQDN: ""
  K8S_SERVICE_PUBLIC_FQDN: ""
  CATALINA_OPTS: ""

# livenessProbe:
#   Path:
#   Port:
# ReadinessProbe:
#   Path:
#   Port:

Resources:
  cpuRequest: 1000m
  cpuLimit: 2000m
  memoryRequest: 2048Mi
  memoryLimit: 3072Mi

SecurityContext: 1000

Persistence:
   # define volume claim template.
   VolumeClaimTemplates:
     AccessModes: ReadWriteOnce
     Storage: 1Gi
     StorageClassName: manual
     Selector:
       Enabled: true
       MatchLabels:
        product: atlassian-jira
        type: server

   # datacenter volume -- Needs Datacenter.Enabled to be set to true or else it would be ignored.
   DatacenterExistingClaimName: ""
   DatacenterMountPath: /var/atlassian/jira-datacenter/
   DatacenterVolumeClaimTemplates:
     AccessModes: ReadWriteMany
     Storage: 20Gi
     StorageClassName: gp2
     Selector:
       Enabled: true
       MatchLabels:
        product: atlassian-jira
        type: datacenter

PodDisruption:
  Enabled: false
  MinAvailable: 1

Service:
  Type: ClusterIP
  Port: 8080
  Protocol: TCP
  Annotations:
    traefik.backend.loadbalancer.sticky: "true"

Ingress:
  Enabled: true
  Host: jira.example.com
  ServicePort: 8080

# to add promethues annotations
PrometheusMetrics:
  Enabled: false
  Path: /plugins/servlet/prometheus/metrics

# list of plugins (plugin IDs) to be pre-installed
PluginIds:
  - com.atlassian.upm.atlassian-universal-plugin-manager-plugin
  - com.atlassian.troubleshooting.plugin-jira
  - ru.andreymarkelov.atlas.plugins.prom-jira-exporter

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
#
nodeSelector: {}
  # Don't forget to remove the brackets above if you want to use a selector.
  # disktype: ssd
  # size: large

## Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
# Don't forget to remove the brackets above if you want to use tolerations.
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"

## Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}
  # Don't forget to remove the brackets above if you want to use affinity.
  # podAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #         - key: security
  #           operator: In
  #           values:
  #           - S1
  #       topologyKey: failure-domain.beta.kubernetes.io/zone
  #   podAntiAffinity:
  #     preferredDuringSchedulingIgnoredDuringExecution:
  #     - weight: 100
  #       podAffinityTerm:
  #         labelSelector:
  #           matchExpressions:
  #           - key: security
  #             operator: In
  #             values:
  #             - S2
  #         topologyKey: kubernetes.io/hostname
