{{- if .Values.Ingress.Enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  {{- if .Values.Ingress.Annotations }}
  annotations:
  {{- range $key, $value := .Values.Ingress.Annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}  
spec:
  rules:
  - host: {{ .Values.Ingress.Host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.Ingress.ServicePort }}
  {{- if .Values.Ingress.Tls.Enabled }}
  tls:
  - secretName: {{ .Values.Ingress.Tls.SecretName }}
    hosts:
    - {{ .Values.Ingress.Host }}
  {{- end }}
{{- end }}
